Repository O-H-M2/qmk_port_ch582, pull requests merged in 2023-05, with the labels that each got.

#95 imk64
  qmk_porting/keyboards/imk64/halconf.h
  qmk_porting/keyboards/imk64/imk64.c
  qmk_porting/keyboards/imk64/imk64.h
  qmk_porting/keyboards/imk64/info.json
  qmk_porting/keyboards/imk64/keymaps/bluetooth_le/keymap.c
  qmk_porting/keyboards/imk64/keymaps/bluetooth_le/rules.cmake
  qmk_porting/keyboards/imk64/keymaps/default/keymap.c
  qmk_porting/keyboards/imk64/keymaps/default/rules.cmake
  qmk_porting/keyboards/imk64/mcuconf.h
  qmk_porting/keyboards/imk64/qmk_config.h
  qmk_porting/keyboards/imk64/rules.cmake
Labels: new keyboard

#98 Add tap dance feature and enable it for imk64:jactry.
  qmk_porting/common_features.cmake
  qmk_porting/keyboards/imk64/keymaps/jactry/keymap.c
  qmk_porting/keyboards/imk64/keymaps/jactry/rules.cmake
Labels: enhancement

#102 Some minor adjustments for README and adding a section for building it on Linux.
  README.md
  README.zh-cn.md
Labels: documentation

#105 README: Add setup of compiler and nrf tools, and add steps for macOS.
  README.md
  README.zh-cn.md
Labels: documentation

#106 place _putchar() into ram when in need
  qmk_porting/platforms/ch58x/platform.c
Labels: enhancement

#107 fix incomplete log output on critical battery level
  qmk_porting/platforms/ch58x/battery_measure.c
Labels: enhancement

#108 add keybaord Tyche pad
  qmk_porting/keyboards/TychePad/TychePad.c
  qmk_porting/keyboards/TychePad/TychePad.h
  qmk_porting/keyboards/TychePad/halconf.h
  qmk_porting/keyboards/TychePad/info.json
  qmk_porting/keyboards/TychePad/keymaps/bluetooth_le/keymap.c
  qmk_porting/keyboards/TychePad/keymaps/bluetooth_le/rules.cmake
  qmk_porting/keyboards/TychePad/keymaps/default/keymap.c
  qmk_porting/keyboards/TychePad/keymaps/default/rules.cmake
  qmk_porting/keyboards/TychePad/mcuconf.h
  qmk_porting/keyboards/TychePad/qmk_config.h
  qmk_porting/keyboards/TychePad/rules.cmake
Labels: new keyboard

#115 QMK update
  qmk_porting/common_features.cmake
  qmk_porting/default_rules.cmake
  qmk_porting/keyboards/mk01/rules.cmake
Labels: enhancement
